V14 Compatibility
TatuLund/TabSheet pull request #4
Opened 2023-01-21 23:26 UTC by samie

- Sync changes from V23
- Updated WebDriverManager
- Remove unused imports in ts
- Ignore all generated files

2023-01-21 23:27 UTC, samie commented
Cannot make TestBench to run integration test. Fails to instantiate driver.

2023-01-25 11:18 UTC, samie commented
Enhancement: Tooltip now works also in V14 as "title" attribute. 
Fix: There was a Java 8 incompatibility and didn't compile with JDK1.8

Tests are still failing with screenshots, but looks like it might be platform dependent font rendering issue.

2023-01-26 08:23 UTC, TatuLund requested changes

2023-01-26 08:23 UTC, TatuLund commented on src/main/resources/META-INF/resources/frontend/tab-sheet.ts
> +	return html `${text ? html`<vaadin-tooltip slot="tooltip" text="${text}"></vaadin-tooltip>` : html``}`;
In Vaadin 14 there is no vaadin-tooltip

2023-01-26 08:23 UTC, TatuLund commented on src/test/java/org/vaadin/addons/tatu/TabSheetInJavaViewIT.java
> +        $("vaadin-dev-tools").first().setProperty("hidden", true);
In Vaadin 14 the devmode widget us named vaadin-devmode-gizmo

2023-01-26 08:23 UTC, TatuLund commented on src/test/java/org/vaadin/addons/tatu/TabSheetInJavaViewIT.java
> +    public void tooltipWorks() {
This is test cannot be used in Vaadin 14 as such, as tooltips can't use vaadin-tooltip and hence vaadin-tooltip-overlay does not exists.

2023-01-26 08:23 UTC, TatuLund commented on src/test/java/org/vaadin/addons/tatu/TabSheetInJavaViewIT.java
> +        Assert.assertTrue(tabSheet.compareScreen(
Yes, it is better to do the screenshot test with the element only, the surroundings will not interfere the test then. Thanks. I had modified this already in V23 version.

2023-01-26 08:23 UTC, TatuLund commented on src/main/resources/META-INF/resources/frontend/tab-sheet.ts
> +	return html`${icon ? html`<iron-icon icon="${icon}"></iron-icon>` : html``}`;
nothing should be used instead of html``. It could be that it is imported from different file in lit version used in Vaadin 14.

2023-01-26 08:23 UTC, TatuLund commented on src/main/resources/META-INF/resources/frontend/tab-sheet.ts
> +			const template = html`<vaadin-tab part="tab" theme="${this.theme}">${this._getIcon(icon)}${caption}${this._getTooltip(tooltip)}</vaadin-tab>`
Bind tooltip to title attribute of vaadin-tab instead

2023-01-26 08:23 UTC, TatuLund commented on src/test/java/org/vaadin/addons/tatu/TabSheetInJavaViewIT.java
> +    public void tooltipWorks() {
If tooltip is implemented with title attribute, it is sufficient to just assert that the attribute has been set

TabElement tab = tabSheet.getTabs().getTabElement("First area");
Assert.assertEquals("The firs tab", tab.getAttribute(title));

2023-01-26 08:23 UTC, TatuLund commented on src/main/resources/META-INF/resources/frontend/tab-sheet.ts
> +  _getTooltip(text : string | undefined | null) : TemplateResult {
Remove unused function.

2023-01-26 08:23 UTC, TatuLund commented on src/test/java/org/vaadin/addons/tatu/TabSheetInJavaViewIT.java
> +    public void tooltipWorks() {
Use the above test code.

2023-01-30 07:50 UTC, merged